INFERENCE:
  checkpoint_type: epoch_idx
  dictionary_path: ../../../dataset/representations/uncond/remi/ailab17k_from-scratch_remi/dictionary.pkl
  experiment_dir: /model-weights
  generated_dir: ./gen_midis
  gpuID: '0'
  model_epoch: 200
  no_cuda: false
  num_sample: 10
MODEL:
  clamp_len: -1
  d_embed: 512
  d_inner: 4096
  d_model: 1024
  div_val: 1
  dropatt: 0.0
  dropout: 0.1
  emb_init: normal
  emb_init_range: 0.01
  eval_tgt_len: 50
  ext_len: 0
  init: normal
  init_range: 0.1
  init_std: 0.02
  mem_len: 512
  n_head: 8
  n_layer: 10
  n_token: 3020
  position_concat: false
  pre_lnorm: true
  proj_init_std: 0.01
  query_dim: 16
  same_length: true
  seq_len: 512
  tgt_len: 70
TRAIN:
  ROOT: ../../../dataset/representations/uncond/remi/ailab17k_from-scratch_remi
  batch_size: 8
  experiment_Dir: /homes/jjl01/ProgTabGeneration/dadaGP-generation-jack/models/5_lat102420230411-151935
  gpuID: '0'
  lr: 0.0001
  no_cuda: false
  num_epochs: 300
  optim: adam
  output_dir: /homes/jjl01/ProgTabGeneration/dadaGP-generation-jack/models/
  resume_training_model: /homes/jjl01/ProgTabGeneration/dadaGP-generation-jack/model-weights/ep_200.pth.tar
  save_freq: 5
  seed: 2222
